version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=QBtkpLIeKTSJGeD0@!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlservervolume:/var/opt/mssql
  sqlservertest:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlservertest
    environment:
      - SA_PASSWORD=QBtkpLIeKTSJGeD0@!
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    volumes:
      - sqlservertestvolume:/var/opt/mssql

volumes:
  sqlservervolume:
  sqlservertestvolume: